// Buscar produtos
GET http://localhost:5005/produtos

###

// Criar um produto
POST http://localhost:5005/produto
Content-Type: application/json

{
    "id": 123,
    "nome": "Produto 1",
    "preco": 459.90,
    "off": 15
}

###

// Buscar produto por id
GET http://localhost:5005/produto/123

###

//Atualizar 
PUT http://localhost:5005/produtos/123
Content-Type: application/json

{
    "nome": "Produto ATUALIZAR",
    "preco": 500.90,
    "off": 30

}

###

//Atualizar Parcial

PATCH http://localhost:5005/produtos/123
Content-Type: application/json

{
    "nome": "Produto ATUALIZADO"
    
}

###
// Deletar todos os produtos

DELETE 